### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by ansidev** [kevinzunigacuellar/kevinzunigacuellar.com#20]
Hi @kevinzunigacuellar,

Is this repository an open-source project?

If it is, please add a file LICENSE to your project.

Thank you!

**Comment by kevinzunigacuellar** [comment]
Thanks, for the comment. I was thinking about adding a license and yes this repo es open-source. Do you have any recommendations?

**Comment by ansidev** [comment]
> Thanks, for the comment. I was thinking about adding a license and yes this repo es open-source. Do you have any recommendations?

@kevinzunigacuellar You can go to https://choosealicense.com/ and select the license that you want. IMO, I believe MIT License is a good option.
